# Site settings
title: Ankush Sharma | Counting infinities
name: Counting infinities
tagline: "Thoughts of a random guy on life experiences, programming and music."
description: "Notes on programming and life."
url: "https://darxtrix.com"
author:
  name: "Ankush Sharma"
  url: "https://github.com/black-perl"

# Build settings
baseurl:
source: .
destination: ./_site
permalink: /:title

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"

# Ignore
exclude:
  - readme.md
  - _artificats
